### PR TITLE
feat: ✅ [Issue 3] Add Category bar

### LINKED ISSUE #3: Category Bar
Create a Category bar (All, Gaming, Music….) similar to YouTube

Reference - https://www.youtube.com/

Branch Name = issue-3

### PR DESCRIPTION
**Pull request by Rana-Paul**
## 🛠️ Fixes Issue
Closes #3 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the coding standards of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
issue-3

### CODE REVIEW

**Review by unnikrishnan2002 — CHANGES_REQUESTED** [review]
- In home.js use `let` keyword to declare variables instead of var
- In html file, point all the href link to # . 
  eg: `href="#"`
- Specify values for `alt` attribute, wherever you have used img 
  eg: `alt="Apoorv's Image"`

**Comment by Rana-Paul** [comment]
changes done. Please check it again.

**Review by unnikrishnan2002 — APPROVED** [review]
Looks good ☑️

**Comment by Rana-Paul** [comment]
Thank you

**Review by apoorv-on-git — APPROVED** [review]

**Pull request merged**
